const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const source = path.join(root, 'node_modules/lucide-static');
const version = JSON.parse(fs.readFileSync(path.join(source, 'package.json'), 'utf8')).version;
const names = ['users','user','link','tag','mail','file-text','check','x','clock','triangle-alert','eye','chevron-down','chevron-right','chevron-left','arrow-left','arrow-right','arrow-left-right','external-link','refresh-cw','plus','sparkles','lock-keyhole','trending-up','git-branch','graduation-cap','book-open','clipboard-check','network','megaphone','activity','menu'];
const nodes = Object.fromEntries(names.map(name => {
  const svg = fs.readFileSync(path.join(source, 'icons', name + '.svg'), 'utf8');
  const body = svg.match(/<svg\b[^>]*>([\s\S]*?)<\/svg>/)[1].trim().replace(/\s*\n\s*/g, '');
  return [name, body];
}));
const license = fs.readFileSync(path.join(source, 'LICENSE'), 'utf8');
const output = `/** Generated by npm run build:icons from lucide-static ${version}. Do not edit. */\nfunction getLucideIconNodes_() {\n  /* ${license.replace(/\*\//g, '* /')} */\n  return ${JSON.stringify(nodes, null, 2)};\n}\n`;
const target = path.join(root, 'lucide-icons.js');
if (process.argv.includes('--check')) {
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== output) throw new Error('Run npm run build:icons to regenerate Lucide assets.');
} else fs.writeFileSync(target, output);
console.log(`${names.length} Lucide icons ${process.argv.includes('--check') ? 'verified' : 'generated'} (v${version}).`);
